export const NOTE_FILE_NAMES = [
    "0 A.mp3",
    "0 A.Sharp.mp3",
    "0 B.mp3",
    "1 C.mp3",
    "1 C.Sharp.mp3",
    "1 D.mp3",
    "1 D.Sharp.mp3",
    "1 E.mp3",
    "1 F.mp3",
    "1 F.Sharp.mp3",
    "1 G.mp3",
    "1 G.Sharp.mp3",
    "1 A.mp3",
    "1 A.Sharp.mp3",
    "1 B.mp3",
    "2 C.mp3",
    "2 C.Sharp.mp3",
    "2 D.mp3",
    "2 D.Sharp.mp3",
    "2 E.mp3",
    "2 F.mp3",
    "2 F.Sharp.mp3",
    "2 G.mp3",
    "2 G.Sharp.mp3",
    "2 A.mp3",
    "2 A.Sharp.mp3",
    "2 B.mp3",
    "3 C.mp3",
    "3 C.Sharp.mp3",
    "3 D.mp3",
    "3 D.Sharp.mp3",
    "3 E.mp3",
    "3 F.mp3",
    "3 F.Sharp.mp3",
    "3 G.mp3",
    "3 G.Sharp.mp3",
    "3 A.mp3",
    "3 A.Sharp.mp3",
    "3 B.mp3",
    "4 C.mp3",
    "4 C.Sharp.mp3",
    "4 D.mp3",
    "4 D.Sharp.mp3",
    "4 E.mp3",
    "4 F.mp3",
    "4 F.Sharp.mp3",
    "4 G.mp3",
    "4 G.Sharp.mp3",
    "4 A.mp3",
    "4 A.Sharp.mp3",
    "4 B.mp3",
    "5 C.mp3",
    "5 C.Sharp.mp3",
    "5 D.mp3",
    "5 D.Sharp.mp3",
    "5 E.mp3",
    "5 F.mp3",
    "5 F.Sharp.mp3",
    "5 G.mp3",
    "5 G.Sharp.mp3",
    "5 A.mp3",
    "5 A.Sharp.mp3",
    "5 B.mp3",
    "6 C.mp3",
    "6 C.Sharp.mp3",
    "6 D.mp3",
    "6 D.Sharp.mp3",
    "6 E.mp3",
    "6 F.mp3",
    "6 F.Sharp.mp3",
    "6 G.mp3",
    "6 G.Sharp.mp3",
    "6 A.mp3",
    "6 A.Sharp.mp3",
    "6 B.mp3",
    "7 C.mp3",
    "7 C.Sharp.mp3",
    "7 D.mp3",
    "7 D.Sharp.mp3",
    "7 E.mp3",
    "7 F.mp3",
    "7 F.Sharp.mp3",
    "7 G.mp3",
    "7 G.Sharp.mp3",
    "7 A.mp3",
    "7 A.Sharp.mp3",
    "7 B.mp3",
    "8 C.mp3",
];

// console.log(NOTE_FILE_NAMES);

export const NOTE_FILES = NOTE_FILE_NAMES.map(
    (fileName) => new Audio("/notes2/" + fileName)
);

export const audioContext = new AudioContext();

// export const NOTE_FILE_BUFFERS = await Promise.all(
//     NOTE_FILE_NAMES.map((value) =>
//         fetch("/notes2/" + value)
//             .then((response) => response.arrayBuffer())
//             .then((data) => audioContext.decodeAudioData(data))
//     )
// );

export const TONIC_SOLFA_NOTES: { [key: string]: number } = {
    Do: 0,
    Di: 1,
    Ra: 1,
    Re: 2,
    Ri: 3,
    Me: 3,
    Mi: 4,
    Fa: 5,
    Fe: 6,
    Se: 6,
    So: 7,
    Si: 8,
    Le: 8,
    La: 9,
    Li: 10,
    Ta: 10,
    Ti: 11,
};

export const NOTE_KEYS: { [key: string]: number } = {
    "G#": 35,
    A_: 35,
    A: 36,
    "A#": 37,
    B_: 37,
    B: 38,
    C: 39,
    "C#": 40,
    D_: 40,
    D: 41,
    "D#": 42,
    E_: 42,
    E: 43,
    F: 44,
    "F#": 45,
    G_: 45,
    G: 46,
};
